configuration:
  - Native
  - WSL

image: Visual Studio 2019

custom_script:
  - echo "custom_script"

for:
-
  matrix:
    only:
      - configuration: Native
  init:
    - echo "init native"
-
  matrix:
    only:
      - configuration: WSL
  init:
    - echo "init wsl"
