image: Visual Studio 2019

init:
  - ps: mkdir InvokeCI
  - ps: >-
      echo '
      function Invoke-CICommand
      {
          if ($env:CONFIGURATION -eq "WSL") {
              wsl $args[0] $args[1..$($args.Count - 1)];
          } else {
              . $args[0] $args[1..$($args.Count - 1)];
          }
      }' > InvokeCI/InvokeCI.psm1
  - ps: Import-Module ./InvokeCI/InvokeCI.psm1
  - ps: rm -r ./InvokeCI
    
install:
  - ps: Invoke-CI-Command echo "hello world"
